# Project 2 : Spark Data Quality Checks & NFL Analysis

**ST 554 : Analysis of Big Data with Python**  
**Author:** David Pressley

---

## Overview

This project explores two aspects of working with PySpark:

1. **Part I**: Design and implement a `SparkDataCheck` class that wraps a Spark SQL DataFrame and provides methods for data validation (bounds checking, level checking, null detection) and summarization (numeric min/max, string counts), then demonstrate the class on the air quality dataset.

2. **Part II**: Analyze weekly NFL data using both the **pandas-on-Spark** API and the **Spark SQL** DataFrame API, comparing quarterback stats across seasons 2005–2023.

---

## Part I : SparkDataCheck Class

### Setup

Start a Spark session and import our SparkDataCheck module.

In [17]:
from pyspark.sql import SparkSession
import pandas as pd

# Start Spark session
spark = SparkSession.builder.appName("p2").getOrCreate()

26/03/28 16:49:08 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.

In [18]:
# Import our custom module (use importlib.reload if you update the .py file)
import importlib
import spark_data_check
importlib.reload(spark_data_check)
from spark_data_check import SparkDataCheck

### Read in the Air Quality Data (CSV method)

We use our `from_csv` class method to create an instance of `SparkDataCheck` from the air quality CSV.

In [19]:
import urllib.request

url = "https://www4.stat.ncsu.edu/online/datasets/air.csv"
urllib.request.urlretrieve(url, "air.csv")
air_check = SparkDataCheck.from_csv(spark, "air.csv")

### Demonstration of Validation Methods

Below we show 4–5 examples of each validation method, including edge cases.

#### Check Range Validation
These validation checks test specified use cases and edge cases for upper and lower bound range checks, and populate a newly created column with a boolean value asserting the value is in the range (or not)

In [39]:
# check_range examples

print("1. Both bounds on a numeric column (Temp between 0 and 40)")
air_check.check_range("T", lower=0, upper=40).df.show(5)

print("2. Only lower bound (Benzene Ground Truth >= 0)")
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.check_range("C6H6(GT)", lower=0).df.show(5)

print("3. Only upper bound (Relative Humidity <= 80)")
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.check_range("RH", upper=80).df.show(5)

print("4. Non-numeric column (should print error message)")
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.check_range("Date", lower=0, upper=10).df.show(5)

print("5. Column with NULLs (NULLs preserved in result)")
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.check_range("CO(GT)", lower=-200, upper=10).df.show(5)

1. Both bounds on a numeric column (Temp between 0 and 40)
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+----------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|CO(GT)_in_range|T_in_range|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+----------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|           true|      true|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|           true|      true|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|           true|      true|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|           true|      true|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|           true|      true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+----------+
only showing top 5 rows
2. Only lower bound (Benzene Ground Truth >= 0)
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|C6H6(GT)_in_range|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|             true|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|             true|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|             true|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|             true|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|             true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------------+
only showing top 5 rows
3. Only upper bound (Relative Humidity <= 80)
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|RH_in_range|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|       true|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|       true|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|       true|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|       true|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|       true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------+
only showing top 5 rows
4. Non-numeric column (should print error message)
Column 'Date' is not numeric. No modification made.
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows
5. Column with NULLs (NULLs preserved in result)
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|CO(GT)_in_range|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|           true|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|           true|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|           true|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|           true|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|           true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+
only showing top 5 rows

#### Check levels Validation
These validation checks test use cases and edge cases for upper and lower bound levels of a column

In [45]:
# check_levels examples

# 1. String column with matching values
air_check = SparkDataCheck.from_csv(spark, "air.csv")
print("1. Levels that exist in the data (Dates 10/03/2004, 11/03/2004, 12/03/2004)")
air_check.check_levels("Date", ["10/03/2004", "11/03/2004", "12/03/2004"]).df.show(25)
# TODO: show more rows to see all 3 dates, or just show the Date column

# 2. String column with values not in the data
air_check = SparkDataCheck.from_csv(spark, "air.csv")
print("2. Levels that do NOT exist in the data (Date 01/01/2099)")
air_check.check_levels("Date", ["01/01/2099"]).df.show(5)

# 3. Non-string column
air_check = SparkDataCheck.from_csv(spark, "air.csv")
print("3. Non-string column (should print error message)")
air_check.check_levels("T", ["hot", "cold"]).df.show(5)

1. Levels that exist in the data (Dates 10/03/2004, 11/03/2004, 12/03/2004)
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|Date_in_levels|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|         false|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|         false|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|         false|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|         false|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|         false|
|3/10/2004|2026-03-28 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|         false|
|3/11/2004|2026-03-28 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|         false|
|3/11/2004|2026-03-28 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|         false|
|3/11/2004|2026-03-28 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|         false|
|3/11/2004|2026-03-28 03:00:00|   0.6|       1010|      19|     1.7|          561|   -200|        1705|   -200|        1235|        501|10.3|60.2|0.7517|         false|
|3/11/2004|2026-03-28 04:00:00|-200.0|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|         false|
|3/11/2004|2026-03-28 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|         false|
|3/11/2004|2026-03-28 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|         false|
|3/11/2004|2026-03-28 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|         false|
|3/11/2004|2026-03-28 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|         false|
|3/11/2004|2026-03-28 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|         false|
|3/11/2004|2026-03-28 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|         false|
|3/11/2004|2026-03-28 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|         false|
|3/11/2004|2026-03-28 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|         false|
|3/11/2004|2026-03-28 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|         false|
|3/11/2004|2026-03-28 14:00:00|   2.9|       1371|     164|    11.5|         1034|    207|         983|    128|        1730|       1037| 8.0|81.1|0.8736|         false|
|3/11/2004|2026-03-28 15:00:00|   2.2|       1310|      79|     8.8|          933|    184|        1082|    126|        1647|        946| 8.3|79.8|0.8778|         false|
|3/11/2004|2026-03-28 16:00:00|   2.2|       1292|      95|     8.3|          912|    193|        1103|    131|        1591|        957| 9.7|71.2|0.8569|         false|
|3/11/2004|2026-03-28 17:00:00|   2.9|       1383|     150|    11.2|         1020|    243|        1008|    135|        1719|       1104| 9.8|67.6|0.8185|         false|
|3/11/2004|2026-03-28 18:00:00|   4.8|       1581|     307|    20.8|         1319|    281|         799|    151|        2083|       1409|10.3|64.2|0.8065|         false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
only showing top 25 rows
2. Levels that do NOT exist in the data (Date 01/01/2099)
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|Date_in_levels|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|         false|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|         false|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|         false|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|         false|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|         false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
only showing top 5 rows
3. Non-string column (should print error message)
Column 'T' is not a string column. No modification made.
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows

#### Check Chaining of range and levels
Check that the ability to chain methods works between range and levels methods

In [41]:
# 4. Method chaining: check_range then check_levels
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.check_range("T", lower=10, upper=30).check_levels("Date", ["10/03/2004"]).df.show(5)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+--------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_in_range|Date_in_levels|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+--------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|      true|         false|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|      true|         false|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|      true|         false|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|      true|         false|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|      true|         false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+--------------+
only showing top 5 rows

#### Check Missing Values
TODO: Need to address that missing values are all -200

In [ ]:
# check_missing examples

# 1. Column likely to have NULLs
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.check_missing("NMHC(GT)").df.show(5)

# 2. Column unlikely to have NULLs
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.check_missing("Date").df.show(5)

# 3. Another numeric column
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.check_missing("CO(GT)").df.show(5)

# 4. Chained with check_range
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.check_missing("T").check_range("T", lower=0, upper=35).df.show(5)

#### Check min-max examples
These validation checks show the use and edge cases for obtaining min and max values with/without grouping variables

In [ ]:


# get_min_max examples

# 1. Single numeric column, no grouping
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.get_min_max("T")

# 2. Single numeric column, grouped by Date
air_check.get_min_max("T", group_col="Date")

# 3. All numeric columns, no grouping
air_check.get_min_max()

# 4. All numeric columns, grouped (reduce/merge case)
air_check.get_min_max(group_col="Date")

# 5. Non-numeric column — should print message, return None
air_check.get_min_max("Date")

# get_counts examples

# 1. Single string column
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.get_counts("Date")

# 2. Non-string column
air_check.get_counts("T")

# 3. Chained with check_levels
air_check = SparkDataCheck.from_csv(spark, "air.csv")
air_check.get_counts("Date", "T")

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_in_range|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|      true|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|      true|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|      true|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|      true|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|      true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+
only showing top 5 rows
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|C6H6(GT)_in_range|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|             true|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|             true|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|             true|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|             true|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|             true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------------+
only showing top 5 rows
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|RH_in_range|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|       true|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|       true|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|       true|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|       true|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|       true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------+
only showing top 5 rows
Column 'Date' is not numeric. No modification made.
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|CO(GT)_in_range|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|           true|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|           true|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|           true|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|           true|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|           true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+
only showing top 5 rows
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|Date_in_levels|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|         false|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|         false|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|         false|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|         false|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|         false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
only showing top 5 rows
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|Date_in_levels|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|         false|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|         false|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|         false|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|         false|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|         false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------+
only showing top 5 rows
Column 'T' is not a string column. No modification made.
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+--------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_in_range|Date_in_levels|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+--------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|      true|         false|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|      true|         false|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|      true|         false|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|      true|         false|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|      true|         false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+--------------+
only showing top 5 rows
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|NMHC(GT)_is_missing|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|              false|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|              false|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|              false|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|              false|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|              false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------------------+
only showing top 5 rows
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|Date_is_missing|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|          false|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|          false|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|          false|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|          false|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|          false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+---------------+
only showing top 5 rows
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|CO(GT)_is_missing|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|            false|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|            false|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|            false|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|            false|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|            false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------------+
only showing top 5 rows
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------------+----------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_is_missing|T_in_range|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+------------+----------+
|3/10/2004|2026-03-28 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|       false|      true|
|3/10/2004|2026-03-28 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|       false|      true|
|3/10/2004|2026-03-28 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|       false|      true|
|3/10/2004|2026-03-28 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|       false|      true|
|3/10/2004|2026-03-28 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|       false|      true|

### Demonstration of Summarization Methods

In [21]:
air_check = SparkDataCheck.from_csv(spark, "air.csv")

display(air_check.get_min_max("C6H6(GT)"))
display(air_check.get_counts("Date"))

   C6H6(GT)_min  C6H6(GT)_max
0        -200.0          63.7

          Date  count
0     1/1/2005     24
1    1/10/2005     24
2    1/11/2005     24
3    1/12/2005     24
4    1/13/2005     24
..         ...    ...
386   9/5/2004     24
387   9/6/2004     24
388   9/7/2004     24
389   9/8/2004     24
390   9/9/2004     24

[391 rows x 2 columns]

### Read in Air Quality Data (pandas method)

Now we read the same data using standard pandas and create an instance via `from_pandas`.

In [22]:
# Create instance from pandas DataFrame
air_pd = pd.read_csv("https://www4.stat.ncsu.edu/online/datasets/air.csv")
air_check_pd = SparkDataCheck.from_pandas(spark, air_pd)

In [23]:
# example method call on the pandas-created instance
air_check_pd.get_min_max("C6H6(GT)")

   C6H6(GT)_min  C6H6(GT)_max
0        -200.0          63.7

---

## Part II : NFL Quarterback Analysis

In this section we analyze weekly NFL data to look at quarterback performance across seasons 2005-2023. We perform the same analysis twice: once using the **pandas-on-Spark** API and once using the **Spark SQL** DataFrame API.

### pandas-on-Spark Approach

In [24]:
import pyspark.pandas as ps

# Read in the NFL data
nfl = ps.read_csv("weekly_nfl_data.csv")

# Check the first 5 rows
nfl.head(5)

/Users/david/projects/ncsu/st554/p2/.venv/lib/python3.12/site-packages/pyspark/pandas/utils.py:1038: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_csv`, the default index is attached which can cause additional overhead.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

In [25]:
# get columns
nfl.columns

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'opponent_team', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

In [26]:
# Filter to QBs, regular season, 2005-2023
qb = nfl[(nfl["position"] == "QB") &
         (nfl["season_type"] == "REG") &
         (nfl["season"] >= 2005) &
         (nfl["season"] <= 2023)]

# Select only the columns we need
cols = ["player_display_name", "season", "week", "completions",
        "attempts", "passing_yards", "passing_tds", "interceptions"]
qb = qb[cols]

# GroupBy player and season, compute sum and mean
stat_cols = ["completions", "attempts", "passing_yards",
             "passing_tds", "interceptions"]
qb_season = qb.groupby(["player_display_name", "season"])[stat_cols].agg(["sum", "mean"])

# Flatten the MultiIndex columns
qb_season.columns = ["_".join(col) for col in qb_season.columns]
qb_season = qb_season.reset_index()

# Create new columns
qb_season["completion_percentage"] = qb_season["completions_sum"] / qb_season["attempts_sum"]
qb_season["td_int_ratio"] = qb_season["passing_tds_sum"] / qb_season["interceptions_sum"]

In [28]:
# Filter to at least 50 attempts
qualified = qb_season[qb_season["attempts_sum"] >= 50]

In [29]:
# Top 40 by completion percentage
qualified.sort_values("completion_percentage", ascending=False).head(40)

     player_display_name  season  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
1409       C.J. Beathard    2023               40          6.666667            53       8.833333              349.0           58.166667                1          0.166667                0.0            0.000000               0.754717           inf
1248          Colt McCoy    2021               74         10.571429            99      14.142857              740.0          105.714286                3          0.428571                1.0            0.142857               0.747475      3.000000
900          Matt Schaub    2019               50         10.000000            67      13.400000              580.0          116.000000                3          0.600000                1.0            0.200000               0.746269      3.000000
953           Drew Brees    2018              364         24.266667           489      32.600000             3992.0          266.133333               32          2.133333                5.0            0.333333               0.744376      6.400000
1057          Drew Brees    2019              281         25.545455           378      34.363636             2979.0          270.818182               27          2.454545                4.0            0.363636               0.743386      6.750000
1338       Mason Rudolph    2023               55         13.750000            74      18.500000              719.0          179.750000                3          0.750000                0.0            0.000000               0.743243           inf
1133         Taysom Hill    2020               88          5.500000           121       7.562500              928.0           58.000000                4          0.250000                2.0            0.125000               0.727273      2.000000
1007          Nick Foles    2018              141         28.200000           195      39.000000             1413.0          282.600000                7          1.400000                4.0            0.800000               0.723077      1.750000
917           Drew Brees    2017              386         24.125000           536      33.500000             4334.0          270.875000               23          1.437500                8.0            0.500000               0.720149      2.875000
851         Sam Bradford    2016              395         26.333333           552      36.800000             3877.0          258.466667               20          1.333333                5.0            0.333333               0.715580      4.000000
510           Drew Brees    2011              471         29.437500           660      41.250000             5535.0          345.937500               46          2.875000               14.0            0.875000               0.713636      3.285714
838           Colt McCoy    2014               91         18.200000           128      25.600000             1057.0          211.400000                4          0.800000                3.0            0.600000               0.710938      1.333333
1262       Aaron Rodgers    2020              372         23.250000           526      32.875000             4299.0          268.687500               48          3.000000                5.0            0.312500               0.707224      9.600000
1453        Bailey Zappe    2022               65         16.250000            92      23.000000              781.0          195.250000                5          1.250000                3.0            0.750000               0.706522      1.666667
242           Drew Brees    2009              363         24.200000           514      34.266667             4388.0          292.533333               34          2.266667               11.0            0.733333               0.706226      3.090909
1098          Drew Brees    2020              275         22.916667           390      32.500000             2942.0          245.166667               24          2.000000                6.0            0.500000               0.705128      4.000000
1437          Joe Burrow    2021              366         22.875000           520      32.500000             4611.0          288.187500               34          2.125000               14.0            0.875000               0.703846      2.428571
1101          Derek Carr    2019              361         22.562500           513      32.062500             4054.0          253.375000               21          1.312500                8.0            0.500000               0.703704      2.625000
1303       Jake Browning    2023              171         19.000000           243      27.000000             1936.0          215.111111               12          1.333333                7.0            0.777778               0.703704      1.714286
901         Chase Daniel    2019               45         15.000000            64      21.333333              435.0          145.000000                3          1.000000                2.0            0.666667               0.703125      1.500000
1079      Ryan Tannehill    2019              201         16.750000           286      23.833333             2742.0          228.500000               22          1.833333                6.0            0.500000               0.702797      3.666667
1088      Deshaun Watson    2020              382         23.875000           544      34.000000             4823.0          301.437500               33          2.062500                7.0            0.437500               0.702206      4.714286
503           Alex Smith    2012              153         15.300000           218      21.800000             1737.0          173.700000               13          1.300000                5.0            0.500000               0.701835      2.600000
942         Kirk Cousins    2018              425         26.562500           606      37.875000             4298.0          268.625000               30          1.875000               10.0            0.625000               0.701320      3.000000
129         Jamie Martin    2005              124         15.500000           177      22.125000             1277.0          159.625000                5          0.625000                7.0            0.875000               0.700565      0.714286
884           Drew Brees    2016              471         29.437500           673      42.062500             5208.0          325.500000               37          2.312500               15.0            0.937500               0.699851      2.466667
770            Tony Romo    2014              304         20.266667           435      29.000000             3705.0          247.000000               34          2.266667                9.0            0.600000               0.698851      3.777778
872            Matt Ryan    2016              373         23.312500           534      33.375000             4944.0          309.000000               38          2.375000                7.0            0.437500               0.698502      5.428571
876         Kirk Cousins    2015              379         23.687500           543      33.937500             4166.0          260.375000               29          1.812500               11.0            0.687500               0.697974      2.636364
1316          Geno Smith    2022              399         23.470588           572      33.647059             4282.0          251.882353               30          1.764706               11.0            0.647059               0.697552      2.727273
926         Chase Daniel    2018               53         13.250000            76      19.000000              515.0          128.750000                3          0.750000                2.0            0.500000               0.697368      1.500000
914         Carson Wentz    2018              279         25.363636           401      36.454545             3074.0          279.454545               21          1.909091                7.0            0.636364               0.695761      3.000000
1397        Dak Prescott    2023              410         24.117647           590      34.705882             4516.0          265.647059               36          2.117647                9.0            0.529412               0.694915      4.000000
553        Philip Rivers    2013              378         23.625000           544      34.000000             4478.0          279.875000               32          2.000000               11.0            0.687500               0.694853      2.909091
362            Tony Romo    2010              148         24.666667           213      35.500000             1605.0          267.500000               11          1.833333                7.0            1.166667               0.694836      1.571429
1295        Kirk Cousins    2023              216         27.000000           311      38.875000             2331.0          291.375000               18          2.250000                5.0            0.625000               0.694534      3.600000
928            Matt Ryan    2018              422         26.375000           608      38.000000             4924.0          307.750000               35          2.187500                7.0            0.437500               0.694079      5.000000
1433         Brock Purdy    2023              308         19.250000           444      27.750000             4280.0          267.500000               31          1.937500               11.0            0.687500               0.693694      2.818182
41             Jim Sorgi    2005               43          8.600000            62      12.400000              444.0           88.800000                3          0.600000                1.0            0.200000               0.693548      3.000000
772       Brandon Weeden    2015               97         16.166667           140      23.333333             1043.0          173.833333                5          0.833333                2.0            0.333333               0.692857      2.500000

### Top 40 TD / INT Ratio

In [30]:
# top 40 by TD/INT ratio
qualified.sort_values("td_int_ratio", ascending=False).head(40)

     player_display_name  season  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
4          Kerry Collins    2007               50          8.333333            82      13.666667              531.0           88.500000                0          0.000000                0.0            0.000000               0.609756           NaN
829           Tom Savage    2016               46         15.333333            73      24.333333              461.0          153.666667                0          0.000000                0.0            0.000000               0.630137           NaN
941      Jacoby Brissett    2016               34         11.333333            55      18.333333              400.0          133.333333                0          0.000000                0.0            0.000000               0.618182           NaN
6          Charlie Batch    2006               30          4.285714            52       7.428571              477.0           68.142857                5          0.714286                0.0            0.000000               0.576923           inf
26           Matt Schaub    2005               33          4.714286            64       9.142857              495.0           70.714286                4          0.571429                0.0            0.000000               0.515625           inf
73          Todd Collins    2007               67         16.750000           105      26.250000              888.0          222.000000                5          1.250000                0.0            0.000000               0.638095           inf
455           Troy Smith    2007               40         10.000000            76      19.000000              452.0          113.000000                2          0.500000                0.0            0.000000               0.526316           inf
520          Jake Locker    2011               34          6.800000            66      13.200000              542.0          108.400000                4          0.800000                0.0            0.000000               0.515152           inf
775          Brian Hoyer    2016              134         22.333333           200      33.333333             1445.0          240.833333                6          1.000000                0.0            0.000000               0.670000           inf
778           Nick Foles    2016               36         18.000000            55      27.500000              410.0          205.000000                3          1.500000                0.0            0.000000               0.654545           inf
812       Derek Anderson    2014               65         13.000000            97      19.400000              701.0          140.200000                5          1.000000                0.0            0.000000               0.670103           inf
940      Jimmy Garoppolo    2016               43          7.166667            63      10.500000              502.0           83.666667                4          0.666667                0.0            0.000000               0.682540           inf
984           Matt Moore    2019               59          9.833333            91      15.166667              659.0          109.833333                4          0.666667                0.0            0.000000               0.648352           inf
1127       C.J. Beathard    2020               66         11.000000           104      17.333333              787.0          131.166667                6          1.000000                0.0            0.000000               0.634615           inf
1334         Andy Dalton    2023               34         17.000000            58      29.000000              361.0          180.500000                2          1.000000                0.0            0.000000               0.586207           inf
1338       Mason Rudolph    2023               55         13.750000            74      18.500000              719.0          179.750000                3          0.750000                0.0            0.000000               0.743243           inf
1365      Desmond Ridder    2022               73         18.250000           115      28.750000              708.0          177.000000                2          0.500000                0.0            0.000000               0.634783           inf
1409       C.J. Beathard    2023               40          6.666667            53       8.833333              349.0           58.166667                1          0.166667                0.0            0.000000               0.754717           inf
763            Tom Brady    2016              291         24.250000           432      36.000000             3554.0          296.166667               28          2.333333                2.0            0.166667               0.673611     14.000000
639           Nick Foles    2013              203         15.615385           317      24.384615             2891.0          222.384615               27          2.076923                2.0            0.153846               0.640379     13.500000
618          Josh McCown    2013              149         18.625000           224      28.000000             1829.0          228.625000               13          1.625000                1.0            0.125000               0.665179     13.000000
989        Aaron Rodgers    2018              372         23.250000           597      37.312500             4442.0          277.625000               25          1.562500                2.0            0.125000               0.623116     12.500000
200          Damon Huard    2006              148         14.800000           244      24.400000             1878.0          187.800000               11          1.100000                1.0            0.100000               0.606557     11.000000
1262       Aaron Rodgers    2020              372         23.250000           526      32.875000             4299.0          268.687500               48          3.000000                5.0            0.312500               0.707224      9.600000
1111       Aaron Rodgers    2021              366         22.875000           531      33.187500             4115.0          257.187500               37          2.312500                4.0            0.250000               0.689266      9.250000
286            Tom Brady    2010              324         20.250000           492      30.750000             3900.0          243.750000               36          2.250000                4.0            0.250000               0.658537      9.000000
20         Jake Delhomme    2007               55         18.333333            86      28.666667              617.0          205.666667                8          2.666667                1.0            0.333333               0.639535      8.000000
695        Aaron Rodgers    2014              341         21.312500           520      32.500000             4381.0          273.812500               38          2.375000                5.0            0.312500               0.655769      7.600000
662        Aaron Rodgers    2011              342         22.800000           501      33.400000             4636.0          309.066667               45          3.000000                6.0            0.400000               0.682635      7.500000
1057          Drew Brees    2019              281         25.545455           378      34.363636             2979.0          270.818182               27          2.454545                4.0            0.363636               0.743386      6.750000
1073       Aaron Rodgers    2019              353         22.062500           569      35.562500             4002.0          250.125000               26          1.625000                4.0            0.250000               0.620387      6.500000
953           Drew Brees    2018              364         24.266667           489      32.600000             3992.0          266.133333               32          2.133333                5.0            0.333333               0.744376      6.400000
1267     Patrick Mahomes    2020              390         26.000000           588      39.200000             4740.0          316.000000               38          2.533333                6.0            0.400000               0.663265      6.333333
145            Tom Brady    2007              398         24.875000           578      36.125000             4806.0          300.375000               50          3.125000                8.0            0.500000               0.688581      6.250000
951       Russell Wilson    2019              341         21.312500           516      32.250000             4110.0          256.875000               31          1.937500                5.0            0.312500               0.660853      6.200000
23         David Garrard    2007              208         17.333333           325      27.083333             2509.0          209.083333               18          1.500000                3.0            0.250000               0.640000      6.000000
418     Matthew Stafford    2010               57         14.250000            96      24.000000              535.0          133.750000                6          1.500000                1.0            0.250000               0.593750      6.000000
1168       Lamar Jackson    2019              265         17.666667           401      26.733333             3127.0          208.466667               36          2.400000                6.0            0.400000               0.660848      6.000000
1026        Dak Prescott    2016              311         19.437500           459      28.687500             3667.0          229.187500               23          1.437500                4.0            0.250000               0.677560      5.750000
766        Aaron Rodgers    2016              401         25.062500           610      38.125000             4428.0          276.750000               40          2.500000                7.0            0.437500               0.657377      5.714286

### Spark SQL DataFrame Approach

In [ ]:
# Read the NFL data using Spark SQL
nfl_spark = spark.read.load(
    "weekly_nfl_data.csv",
    format="csv",
    sep=",",
    inferSchema="true",
    header="true"
)

# Check first 5 rows
nfl_spark.show(5)

# get columns
nfl_spark.columns

+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
| player_id|player_name| player_display_name|position|position_group|headshot_url|recent_team|season|week|season_type|opponent_team|completions|attempts|passing_yards|passing_tds|interceptions|sacks|sack_yards|sack_fumbles|sack_fumbles_lost|passing_air_yards|passing_yards_after_catch|passing_first_downs|passing_epa|passing_2pt_conversions|pacr|dakota|carries|rushing_yards|rushing_tds|rushing_fumbles|rushing_fumbles_lost|rushing_first_downs|rushing_epa|rushing_2pt_conversions|receptions|targets|receiving_yards|receiving_tds|receiving_fumbles|receiving_fumbles_lost|receiving_air_yards|receiving_yards_after_catch|receiving_first_downs|receiving_epa|receiving_2pt_conversions|racr|target_share|air_yards_share|wopr|special_teams_tds|fantasy_points|fantasy_points_ppr|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   1|        REG|          DEN|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     16|         60.0|          1|            0.0|                 0.0|                4.0|   6.248771|                      0|         1|      1|            7.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|   0.29237816|                        0| 0.0|  0.05263158|           NULL|NULL|              0.0|          12.7|              13.7|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   2|        REG|          ARI|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      9|         33.0|          0|            0.0|                 0.0|                1.0| -1.4349501|                      0|         3|      4|           18.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  1.0|    0.3770089|                        0| 0.0|  0.11764706|           NULL|NULL|              0.0|           5.1|               8.1|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   4|        REG|          BUF|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      3|          2.0|          0|            0.0|                 0.0|                0.0| -1.5399517|                      0|         0|      1|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.69957775|                        0|NULL| 0.023809524|           NULL|NULL|              0.0|           0.2|               0.2|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   7|        REG|           LA|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      6|         27.0|          0|            0.0|                 0.0|                0.0|  0.2160509|                      0|         2|      2|            8.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.22845396|                        0| 0.0|        0.05|           NULL|NULL|              0.0|           3.5|               5.5|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   8|        REG|           NO|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     13|         39.0|          0|            0.0|                 0.0|                2.0| -2.9722588|                      0|         0|      0|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|         NULL|                        0|NULL|        NULL|           NULL|NULL|              0.0|           3.9|               3.9|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
only showing top 5 rows

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

In [ ]:
from pyspark.sql import functions as F
# Filter and select
qb_spark = nfl_spark.filter(
    (F.col("position") == "QB") &
    (F.col("season_type") == "REG") &
    (F.col("season") >= 2005) &
    (F.col("season") <= 2023)
).select("player_display_name", "season", "week", "completions",
         "attempts", "passing_yards", "passing_tds", "interceptions")

# GroupBy and aggregate
qb_season_spark = qb_spark.groupBy("player_display_name", "season").agg(
    F.sum("completions").alias("completions_sum"),
    F.mean("completions").alias("completions_mean"),
    F.sum("attempts").alias("attempts_sum"),
    F.mean("attempts").alias("attempts_mean"),
    F.sum("passing_yards").alias("passing_yards_sum"),
    F.mean("passing_yards").alias("passing_yards_mean"),
    F.sum("passing_tds").alias("passing_tds_sum"),
    F.mean("passing_tds").alias("passing_tds_mean"),
    F.sum("interceptions").alias("interceptions_sum"),
    F.mean("interceptions").alias("interceptions_mean")
)

# Create new columns
# Use try_divide for td_int_ratio to handle QBs with 0 interceptions
qb_season_spark = qb_season_spark.withColumn(
    "completion_percentage",
    F.col("completions_sum") / F.col("attempts_sum")
).withColumn(
    "td_int_ratio",
    F.try_divide(F.col("passing_tds_sum"), F.col("interceptions_sum"))
)

# Filter to at least 50 attempts
qualified_spark = qb_season_spark.filter(F.col("attempts_sum") >= 50)

# Top 40 by completion percentage
qualified_spark.orderBy(F.col("completion_percentage").desc()).show(40)

# Top 40 by td_int_ratio
qualified_spark.orderBy(F.col("td_int_ratio").desc()).show(40)

+-------------------+------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+-------------------+-----------------+-------------------+---------------------+------------------+
|player_display_name|season|completions_sum|  completions_mean|attempts_sum|     attempts_mean|passing_yards_sum|passing_yards_mean|passing_tds_sum|   passing_tds_mean|interceptions_sum| interceptions_mean|completion_percentage|      td_int_ratio|
+-------------------+------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+-------------------+-----------------+-------------------+---------------------+------------------+
|      C.J. Beathard|  2023|             40| 6.666666666666667|          53| 8.833333333333334|            349.0|58.166666666666664|              1|0.16666666666666666|              0.0|                0.0|   0.7547169811320755|              NULL|
|         Colt McCoy|  2021|             74|10.571428571428571|          99|14.142857142857142|            740.0|105.71428571428571|              3|0.42857142857142855|              1.0|0.14285714285714285|   0.7474747474747475|               3.0|
|        Matt Schaub|  2019|             50|              10.0|          67|              13.4|            580.0|             116.0|              3|                0.6|              1.0|                0.2|    0.746268656716418|               3.0|
|         Drew Brees|  2018|            364|24.266666666666666|         489|              32.6|           3992.0| 266.1333333333333|             32| 2.1333333333333333|              5.0| 0.3333333333333333|   0.7443762781186094|               6.4|
|         Drew Brees|  2019|            281|25.545454545454547|         378| 34.36363636363637|           2979.0| 270.8181818181818|             27| 2.4545454545454546|              4.0|0.36363636363636365|   0.7433862433862434|              6.75|
|      Mason Rudolph|  2023|             55|             13.75|          74|              18.5|            719.0|            179.75|              3|               0.75|              0.0|                0.0|   0.7432432432432432|              NULL|
|        Taysom Hill|  2020|             88|               5.5|         121|            7.5625|            928.0|              58.0|              4|               0.25|              2.0|              0.125|   0.7272727272727273|               2.0|
|         Nick Foles|  2018|            141|              28.2|         195|              39.0|           1413.0|             282.6|              7|                1.4|              4.0|                0.8|   0.7230769230769231|              1.75|
|         Drew Brees|  2017|            386|            24.125|         536|              33.5|           4334.0|           270.875|             23|             1.4375|              8.0|                0.5|   0.7201492537313433|             2.875|
|       Sam Bradford|  2016|            395|26.333333333333332|         552|              36.8|           3877.0|258.46666666666664|             20| 1.3333333333333333|              5.0| 0.3333333333333333|   0.7155797101449275|               4.0|
|         Drew Brees|  2011|            471|           29.4375|         660|             41.25|           5535.0|          345.9375|             46|              2.875|             14.0|              0.875|   0.7136363636363636|3.2857142857142856|
|         Colt McCoy|  2014|             91|              18.2|         128|              25.6|           1057.0|             211.4|              4|                0.8|              3.0|                0.6|            0.7109375|1.3333333333333333|
|      Aaron Rodgers|  2020|            372|             23.25|         526|            32.875|           4299.0|          268.6875|             48|                3.0|              5.0|             0.3125|   0.7072243346007605|               9.6|
|       Bailey Zappe|  2022|             65|             16.25|          92|              23.0|            781.0|            195.25|              5|               1.25|              3.0|               0.75|   0.7065217391304348|1.6666666666666667|
|         Drew Brees|  2009|            363|              24.2|         514|34.266666666666666|           4388.0|292.53333333333336|             34| 2.2666666666666666|             11.0| 0.7333333333333333|   0.7062256809338522| 3.090909090909091|
|         Drew Brees|  2020|            275|22.916666666666668|         390|              32.5|           2942.0|245.16666666666666|             24|                2.0|              6.0|                0.5|   0.7051282051282052|               4.0|
|         Joe Burrow|  2021|            366|            22.875|         520|              32.5|           4611.0|          288.1875|             34|              2.125|             14.0|              0.875|   0.7038461538461539|2.4285714285714284|
|         Derek Carr|  2019|            361|           22.5625|         513|           32.0625|           4054.0|           253.375|             21|             1.3125|              8.0|                0.5|   0.7037037037037037|             2.625|
|      Jake Browning|  2023|            171|              19.0|         243|              27.0|           1936.0|215.11111111111111|             12| 1.3333333333333333|              7.0| 0.7777777777777778|   0.7037037037037037|1.7142857142857142|
|       Chase Daniel|  2019|             45|              15.0|          64|21.333333333333332|            435.0|             145.0|              3|                1.0|              2.0| 0.6666666666666666|             0.703125|               1.5|
|     Ryan Tannehill|  2019|            201|             16.75|         286|23.833333333333332|           2742.0|             228.5|             22| 1.8333333333333333|              6.0|                0.5|   0.7027972027972028|3.6666666666666665|
|     Deshaun Watson|  2020|            382|            23.875|         544|              34.0|           4823.0|          301.4375|             33|             2.0625|              7.0|             0.4375|   0.7022058823529411| 4.714285714285714|
|         Alex Smith|  2012|            153|              15.3|         218|              21.8|           1737.0|             173.7|             13|                1.3|              5.0|                0.5|   0.7018348623853211|               2.6|
|       Kirk Cousins|  2018|            425|           26.5625|         606|            37.875|           4298.0|           268.625|             30|              1.875|             10.0|              0.625|   0.7013201320132013|               3.0|
|       Jamie Martin|  2005|            124|              15.5|         177|            22.125|           1277.0|           159.625|              5|              0.625|              7.0|              0.875|   0.7005649717514124|0.7142857142857143|
|         Drew Brees|  2016|            471|           29.4375|         673|           42.0625|           5208.0|             325.5|             37|             2.3125|             15.0|             0.9375|   0.6998514115898959| 2.466666666666667|
|          Tony Romo|  2014|            304|20.266666666666666|         435|              29.0|           3705.0|             247.0|             34| 2.2666666666666666|              9.0|                0.6|   0.6988505747126437|3.7777777777777777|
|          Matt Ryan|  2016|            373|           23.3125|         534|            33.375|           4944.0|             309.0|             38|              2.375|              7.0|             0.4375|   0.6985018726591761| 5.428571428571429|
|       Kirk Cousins|  2015|            379|           23.6875|         543|           33.9375|           4166.0|           260.375|             29|             1.8125|             11.0|             0.6875|   0.6979742173112339|2.6363636363636362|
|         Geno Smith|  2022|            399|23.470588235294116|         572| 33.64705882352941|           4282.0|251.88235294117646|             30| 1.7647058823529411|             11.0| 0.6470588235294118|   0.6975524475524476| 2.727272727272727|
|       Chase Daniel|  2018|             53|             13.25|          76|              19.0|            515.0|            128.75|              3|               0.75|              2.0|                0.5|   0.6973684210526315|               1.5|
|       Carson Wentz|  2018|            279|25.363636363636363|         401| 36.45454545454545|           3074.0|279.45454545454544|             21| 1.9090909090909092|              7.0| 0.6363636363636364|   0.6957605985037406|               3.0|
|       Dak Prescott|  2023|            410| 24.11764705882353|         590|34.705882352941174|           4516.0| 265.6470588235294|             36| 2.1176470588235294|              9.0| 0.5294117647058824|   0.6949152542372882|               4.0|
|      Philip Rivers|  2013|            378|            23.625|         544|              34.0|           4478.0|           279.875|             32|                2.0|             11.0|             0.6875|   0.6948529411764706| 2.909090909090909|
|          Tony Romo|  2010|            148|24.666666666666668|         213|              35.5|           1605.0|             267.5|             11| 1.8333333333333333|              7.0| 1.1666666666666667|   0.6948356807511737|1.5714285714285714|
|       Kirk Cousins|  2023|            216|              27.0|         311|            38.875|           2331.0|           291.375|             18|               2.25|              5.0|              0.625|   0.6945337620578779|               3.6|
|          Matt Ryan|  2018|            422|            26.375|         608|              38.0|           4924.0|            307.75|             35|             2.1875|              7.0|             0.4375|    0.694078947368421|               5.0|
|        Brock Purdy|  2023|            308|             19.25|         444|             27.75|           4280.0|             267.5|             31|             1.9375|             11.0|             0.6875|   0.6936936936936937|2.8181818181818183|
|          Jim Sorgi|  2005|             43|               8.6|          62|              12.4|            444.0|              88.8|              3|                0.6|              1.0|                0.2|   0.6935483870967742|               3.0|
|     Brandon Weeden|  2015|             97|16.166666666666668|         140|23.333333333333332|           1043.0|173.83333333333334|              5| 0.8333333333333334|              2.0| 0.3333333333333333|   0.6928571428571428|               2.5|
+-------------------+------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+-------------------+-----------------+-------------------+---------------------+------------------+
only showing top 40 rows
+-------------------+------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+------------------+-----------------+-------------------+---------------------+-----------------+
|player_display_name|season|completions_sum|  completions_mean|attempts_sum|     attempts_mean|passing_yards_sum|passing_yards_mean|passing_tds_sum|  passing_tds_mean|interceptions_sum| interceptions_mean|completion_percentage|     td_int_ratio|
+-------------------+------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+------------------+-----------------+-------------------+---------------------+-----------------+
|          Tom Brady|  2016|            291|             24.25|         432|              36.0|           3554.0| 296.1666666666667|             28|2.3333333333333335|              2.0|0.16666666666666666|   0.6736111111111112|             14.0|
|         Nick Foles|  2013|            203|15.615384615384615|         317|24.384615384615383|           2891.0| 222.3846153846154|             27| 2.076923076923077|              2.0|0.15384615384615385|   0.6403785488958991|             13.5|
|        Josh McCown|  2013|            149|            18.625|         224|              28.0|           1829.0|           228.625|             13|             1.625|              1.0|              0.125|   0.6651785714285714|             13.0|
|      Aaron Rodgers|  2018|            372|             23.25|         597|           37.3125|           4442.0|           277.625|             25|            1.5625|              2.0|              0.125|   0.6231155778894473|             12.5|
|        Damon Huard|  2006|            148|              14.8|         244|              24.4|           1878.0|             187.8|             11|               1.1|              1.0|                0.1|   0.6065573770491803|             11.0|
|      Aaron Rodgers|  2020|            372|             23.25|         526|            32.875|           4299.0|          268.6875|             48|               3.0|              5.0|             0.3125|   0.7072243346007605|              9.6|
|      Aaron Rodgers|  2021|            366|            22.875|         531|           33.1875|           4115.0|          257.1875|             37|            2.3125|              4.0|               0.25|   0.6892655367231638|             9.25|
|          Tom Brady|  2010|            324|             20.25|         492|             30.75|           3900.0|            243.75|             36|              2.25|              4.0|               0.25|   0.6585365853658537|              9.0|
|      Jake Delhomme|  2007|             55|18.333333333333332|          86|28.666666666666668|            617.0|205.66666666666666|              8|2.6666666666666665|              1.0| 0.3333333333333333|   0.6395348837209303|              8.0|
|      Aaron Rodgers|  2014|            341|           21.3125|         520|              32.5|           4381.0|          273.8125|             38|             2.375|              5.0|             0.3125|   0.6557692307692308|              7.6|
|      Aaron Rodgers|  2011|            342|              22.8|         501|              33.4|           4636.0|309.06666666666666|             45|               3.0|              6.0|                0.4|   0.6826347305389222|              7.5|
|         Drew Brees|  2019|            281|25.545454545454547|         378| 34.36363636363637|           2979.0| 270.8181818181818|             27|2.4545454545454546|              4.0|0.36363636363636365|   0.7433862433862434|             6.75|
|      Aaron Rodgers|  2019|            353|           22.0625|         569|           35.5625|           4002.0|           250.125|             26|             1.625|              4.0|               0.25|   0.6203866432337434|              6.5|
|         Drew Brees|  2018|            364|24.266666666666666|         489|              32.6|           3992.0| 266.1333333333333|             32|2.1333333333333333|              5.0| 0.3333333333333333|   0.7443762781186094|              6.4|
|    Patrick Mahomes|  2020|            390|              26.0|         588|              39.2|           4740.0|             316.0|             38| 2.533333333333333|              6.0|                0.4|   0.6632653061224489|6.333333333333333|
|          Tom Brady|  2007|            398|            24.875|         578|            36.125|           4806.0|           300.375|             50|             3.125|              8.0|                0.5|   0.6885813148788927|             6.25|
|     Russell Wilson|  2019|            341|           21.3125|         516|             32.25|           4110.0|           256.875|             31|            1.9375|              5.0|             0.3125|   0.6608527131782945|              6.2|
|      David Garrard|  2007|            208|17.333333333333332|         325|27.083333333333332|           2509.0|209.08333333333334|             18|               1.5|              3.0|               0.25|                 0.64|              6.0|
|   Matthew Stafford|  2010|             57|             14.25|          96|              24.0|            535.0|            133.75|              6|               1.5|              1.0|               0.25|              0.59375|              6.0|
|      Lamar Jackson|  2019|            265|17.666666666666668|         401|26.733333333333334|           3127.0|208.46666666666667|             36|               2.4|              6.0|                0.4|   0.6608478802992519|              6.0|
|       Dak Prescott|  2016|            311|           19.4375|         459|           28.6875|           3667.0|          229.1875|             23|            1.4375|              4.0|               0.25|   0.6775599128540305|             5.75|
|      Aaron Rodgers|  2016|            401|           25.0625|         610|            38.125|           4428.0|            276.75|             40|               2.5|              7.0|             0.4375|   0.6573770491803279|5.714285714285714|
|     Peyton Manning|  2013|            450|            28.125|         659|           41.1875|           5477.0|          342.3125|             55|            3.4375|             10.0|              0.625|   0.6828528072837633|              5.5|
|          Matt Ryan|  2016|            373|           23.3125|         534|            33.375|           4944.0|             309.0|             38|             2.375|              7.0|             0.4375|   0.6985018726591761|5.428571428571429|
|    Patrick Mahomes|  2019|            319|22.785714285714285|         484| 34.57142857142857|           4031.0|287.92857142857144|             26|1.8571428571428572|              5.0|0.35714285714285715|   0.6590909090909091|              5.2|
|         Alex Smith|  2017|            341|22.733333333333334|         505|33.666666666666664|           4042.0|269.46666666666664|             26|1.7333333333333334|              5.0| 0.3333333333333333|   0.6752475247524753|              5.2|
|          Tom Brady|  2015|            402|            25.125|         624|              39.0|           4770.0|           298.125|             36|              2.25|              7.0|             0.4375|   0.6442307692307693|5.142857142857143|
|        Jeff Garcia|  2006|            116|              14.5|         188|              23.5|           1309.0|           163.625|             10|              1.25|              2.0|               0.25|   0.6170212765957447|              5.0|
|          Matt Ryan|  2018|            422|            26.375|         608|              38.0|           4924.0|            307.75|             35|            2.1875|              7.0|             0.4375|    0.694078947368421|              5.0|
|     Russell Wilson|  2018|            280|              17.5|         427|           26.6875|           3448.0|             215.5|             35|            2.1875|              7.0|             0.4375|   0.6557377049180327|              5.0|
|         Geno Smith|  2021|             65|             16.25|          95|             23.75|            702.0|             175.5|              5|              1.25|              1.0|               0.25|   0.6842105263157895|              5.0|
|      Aaron Rodgers|  2012|            371|           23.1875|         552|              34.5|           4295.0|          268.4375|             39|            2.4375|              8.0|                0.5|   0.6721014492753623|            4.875|
|     Ryan Tannehill|  2020|            315|           19.6875|         481|           30.0625|           3819.0|          238.6875|             34|             2.125|              7.0|             0.4375|   0.6548856548856549|4.857142857142857|

### Comparison: pandas-on-Spark vs Spark SQL

#### Division by Zero in `td_int_ratio`

When computing `td_int_ratio = passing_tds_sum / interceptions_sum`, some 
quarterback-season combinations have zero interceptions, creating a division 
by zero problem. The two APIs handle this differently:

- **pandas-on-Spark** follows Python/NumPy conventions and produces a positive 
  infinity (`inf`) value. These values sort to the top when ordering descending, 
  so the top `td_int_ratio` results are dominated by QBs who happened to 
  throw zero interceptions in a season and seem to be players with minimal playing
  time.

- **Spark SQL** follows SQL conventions and produces `NULL`. These values 
  sort to the bottom when ordered by descending values ()`orderBy(...desc())`), so 
  those same QBs are effectively excluded from the top of the results. The Spark 
  SQL top 40 instead surfaces players who maintained higher ratios over the season.

This means the top 40 `td_int_ratio` lists look different between the 
two approaches with the default sort scenario, even though the underlying 
data and logic are identical.

For `completion_percentage`, the results are consistent across both APIs 
because our filter of `attempts_sum >= 50` guarantees a non-zero denominator. 
Players like Brock Purdy, who completed 69.4% of his passes during his 
breakout 2023 season (308 completions on 444 attempts with 31 touchdowns), 
appear in the same position in both outputs. (Faithful to The Bay!)

In [ ]:
# Stop Spark session
spark.stop()